### ISSUE TITLE
on main page / prompt page, show shortest path length found by scraper and also by players

### ISSUE THREAD

**Issue by mliu59** [wikispeedruns/wikipedia-speedruns#106]

**Comment by bricehalder** [comment]
To clarify, this should be shown only after a user has already played a prompt right?

**Comment by mliu59** [comment]
Not necessarily? could just be an interesting metric for players to see

**Comment by mliu59** [comment]
Upon thinking more, this might be an excessive feature, since the global leaderboard is already there. Closing for now
