### ISSUE TITLE
Add option to sort leaderboard by shortest path/number of clicks

### ISSUE THREAD

**Issue by bricehalder** [wikispeedruns/wikipedia-speedruns#120]

**Comment by mliu59** [comment]
Added to #198 
![image](https://user-images.githubusercontent.com/61032765/155865001-0632ba70-2e3f-4d72-bc17-1ce60ad25f92.png)

**Comment by mliu59** [comment]
Clicking on "Time":
![image](https://user-images.githubusercontent.com/61032765/155865021-77dac090-16dc-4dd3-aa0c-412da9238375.png)
