### ISSUE TITLE
Blur page when prompted to leave the page 

### ISSUE THREAD

**Issue by melodymhsu** [wikispeedruns/wikipedia-speedruns#130]
The timer stops running when a player tries to leave the page (close tab/window or clicking back button), but the player can still read the rest of the screen. This can be taken advantage of by players who try to parse the available routes shown on the page without having the timer running, as they can easily hit "cancel" instead of leaving the page and quickly navigate to the next page of their choosing.

**Comment by maggarwal99** [comment]
The timer actually continues in the background even when player tries to leave the page.
