### ISSUE TITLE
images not displaying, messing up caption format

### ISSUE THREAD

**Issue by mliu59** [wikispeedruns/wikipedia-speedruns#132]

**Comment by mliu59** [comment]
Think this is because there is a relative path call somewhere in the generation

**Comment by maggarwal99** [comment]
@mliu59 is this only for images with links or all images? Could you link an example with this issue?

**Comment by mliu59** [comment]
@maggarwal99 https://wikispeedruns.com/play/1

The Walt Whitman page should look like this: 
![image](https://user-images.githubusercontent.com/61032765/151713290-d49db0c1-48c4-44df-92ca-17a6dfc3290a.png)

Instead the image is not showing, yet caption is still there. Same for almost all pages with a few exceptions
![image](https://user-images.githubusercontent.com/61032765/151713312-05170ac1-ffdb-4863-94fa-ac695fa2606b.png)
