### ISSUE TITLE
Refactor play.js, modularize wiki page loading js functions

### ISSUE THREAD

**Issue by mliu59** [wikispeedruns/wikipedia-speedruns#140]

**Comment by BaileyFurrow** [comment]
Do these files need to be moved into the `modules` folder or does the code in each need to be integrated into the Javascript files already in the `modules` folder?

**Comment by mliu59** [comment]
> Do these files need to be moved into the `modules` folder or does the code in each need to be integrated into the Javascript files already in the `modules` folder?

Either works, but for organization, I think it may be helpful to have them separate. See #148, the redundant functions are currently in play.js and marathon.js

**Comment by mliu59** [comment]
Draft via #183
