### ISSUE TITLE
Save marathon runs and allow players to continue later

### ISSUE THREAD

**Issue by mliu59** [wikispeedruns/wikipedia-speedruns#141]

**Comment by mliu59** [comment]
@dqian3 you mentioned you might have a way to do this on the frontend. How would that work?

**Comment by dqian3** [comment]
That would use localStorage https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

For the server side, we would probably use something flexible like redis https://redis.io/ rather than a new SQL table

**Comment by mliu59** [comment]
Would using client side/frontend saves open up more ways for people to cheat?

**Comment by mliu59** [comment]
local storage, closed with #230
