### ISSUE TITLE
Disable links that go into the wikipedia namespace

### ISSUE THREAD

**Issue by dqian3** [wikispeedruns/wikipedia-speedruns#157]
For example, if you click on the [citation needed] links you get thrown into some articles about wikipedia contribution guidelines.

In these, the links are basically all closed, so the user gets stuck. You can see that for yourself here: https://en.wikipedia.org/wiki/Wikipedia:Verifiability 

The links start with "wiki/Wikipedia:", so it should be easy

**Comment by mliu59** [comment]
similarly, disable links that go into "Category:"

**Comment by mliu59** [comment]
there are a number of checks already in play.js, but i dont think they cover everything

**Comment by mliu59** [comment]
Added a stopgap solution to ignore these links. We should find a way to completely strip these hyperlinks into plain text

**Comment by mliu59** [comment]
Added function to strip namespace links to span
