### ISSUE TITLE
Handle links with an extra anchor tag

### ISSUE THREAD

**Issue by dqian3** [wikispeedruns/wikipedia-speedruns#207]
See *vers libre* on this page
https://en.wikipedia.org/wiki/Free_verse#Vers_libre

**Comment by mliu59** [comment]
For this, the actual link on the article is https://en.wikipedia.org/wiki/Vers_libre

Its the redirect that eventually lands it on https://en.wikipedia.org/wiki/Free_verse#Vers_libre

I'm not sure if there even is anything we can do about this?
