### ISSUE TITLE
Leaderboard with non-matching prompt and run URL parameters displays incorrectly

### ISSUE THREAD

**Issue by codethejason** [wikispeedruns/wikipedia-speedruns#215]
When calling http://127.0.0.1:5000/prompt/3?run_id=2, in the database run_id 2 corresponds with prompt_id 1, but calling it with prompt_id 3 returns results from both prompt_id 2 and prompt_id 3 instead of the expected behavior of prompt_id 3 or an error message.

![Screen Shot 2022-02-27 at 2 34 38 AM](https://user-images.githubusercontent.com/7005740/155878881-e783c0cd-4987-46e8-a664-95f92b2d8789.png)

**Comment by arpansahoo** [comment]
Could I take this issue? @codethejason

**Comment by dqian3** [comment]
@bricehalder Wanna take a look at this too?

**Comment by bricehalder** [comment]
Sure
