### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by dqian3** [wikispeedruns/wikipedia-speedruns#22]
Steam style

Make some fun ones

Make achievement class, with name, desc, method to calculate whether it is achieved, etc.

Table of player ID to achievement name

**Comment by mliu59** [comment]
Wanted to take a stab at this again. This could also be something for Daniel to work on. Here's what I think I'd do, @bricehalder and @dqian3 lmk if this sounds doable or if you have any additional feedback:

New DB table with these columns: 'user_id', 'achievement_id', 'time_achieved'. 
Each achievement reached is stored as its own row

We create an instance of the achievement class for each achievement, and just have them hangout in server memory. Whenever someone finishes a run, we check the person's run history (using the new leaderboard query API) against all achievements that have not be reached, and then return to client a list of achievement_ids that were just achieved to show on the finish page. 

Just so we dont have to pass achievement names and descriptions from the backend, we will also have a frontend copy of a list with all achievements' id, name, description, img address

**Comment by mliu59** [comment]
I was thinking that achievements should only apply to archive/daily prompts, to avoid people creating custom lobby prompts specifically to farm achievements

**Comment by dqian3** [comment]
First steps for @danielliu04 

Write an Achievement class 
- For now, only worry about achievements per run
- Implement simple "visited" an article achievement.

**Comment by mliu59** [comment]
@danielliu04 @dqian3 Can finally close this issue?????!!??!??!
