### ISSUE TITLE
Make leaderboard mobile compatible

### ISSUE THREAD

**Issue by mliu59** [wikispeedruns/wikipedia-speedruns#223]

**Comment by dqian3** [comment]
For example, Gets cutoff on the side ![Screenshot_20220331-004556_Chrome.jpg](https://user-images.githubusercontent.com/11544076/160978592-83b83daf-1b4c-40e0-b32f-3194d3386fc2.jpg)

**Comment by mliu59** [comment]
I actually think alot of mobile issues can be solved with #305 . For example, instead of displaying the full paths on mobile, we can add a tooltip icon for each run. Any additional info related to the run would be displayed there instead
