### ISSUE TITLE
Refine leaderboard(s)

### ISSUE THREAD

**Issue by dqian3** [wikispeedruns/wikipedia-speedruns#240]
Currently, the lobby leaderboard simply displays all runs

Ideally we would want options to filter out repeat runs, see the number of unique players etc.

**Comment by dqian3** [comment]
After discussion, the plan is to make a generic "leaderboard" endpoint that gives the following features, 

1. General Filtering
    - Display unfinished runs
    - Display anonymous runs (doesn't apply to lobby)
    - Display only recent runs
    - Display only attempts within the prompt of the day
2. Grouped filtering by user (a little more annoying to implement)
    - Display only the first attempt
    - Display the best prompt with respect to number of clicks
3. Sorting
    - Start time, play time, clicks (finished first), custom criteria, i.e. time penalty per click
4. Pagination + Offset
    - customisable

**Comment by mliu59** [comment]
We should also try to make this endpoint with personal leaderboard in mind: #214
