### ISSUE TITLE
SQL error when creating a new sprint run on db created with populate_db

### ISSUE THREAD

**Issue by mliu59** [wikispeedruns/wikipedia-speedruns#249]
pymysql throws this error when trying to create a new sprint run. db was cleaned and recreated with create_db.py and populate_db.py

pymysql.err.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`wikipedia_speedruns`.`sprint_runs`, CONSTRAINT `sprint_runs_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`))')

some of the scripts may be outdated? @dqian3

**Comment by mliu59** [comment]
There are also a number of issues with populate_db.py, specifically surrounding datetime fields of runs and users

**Comment by dqian3** [comment]
Hmm, if, the users aren't being created properly it makes sense as to why we're seeing issues with foreign key constraints. 

I saw an issue with the `join_date` field as well, which we've had trouble with before. It seems like the `DEFAULT` keyword doesn't always work, or some people don't have that. I think the solution would be to specify the join date in the script explicitly.
