### ISSUE TITLE
Newly added articles do not have underscores removed

### ISSUE THREAD

**Issue by mliu59** [wikispeedruns/wikipedia-speedruns#262]
![image](https://user-images.githubusercontent.com/61032765/160267073-3c00b871-49dd-4d30-85f5-fe42582c6b08.png)

**Comment by mliu59** [comment]
I think this may be an issue with "getArticleName". 

This currently does not affect how the game checks if the end condition is met, since the strings are sanitized upon check

**Comment by mliu59** [comment]
@dqian3 it seems like the wikipedia REST API doesnt automatically handle redirects like the Action API one

See: https://en.wikipedia.org/api/rest_v1/page/title/United_states
https://en.wikipedia.org/api/rest_v1/page/title/UnitedStates
https://en.wikipedia.org/api/rest_v1/page/title/Unitedstates
https://en.wikipedia.org/api/rest_v1/page/title/United_States

If there isn't some argument we can pass, we might need to switch back to the action API (what we use for retreiving the full article)

**Comment by dqian3** [comment]
Fixed in [0c0c77d](https://github.com/wikispeedruns/wikipedia-speedruns/commit/0c0c77dc51720223e5479436e9fd06da079375b8)
