### ISSUE TITLE
Update SEO description

### ISSUE THREAD

**Issue by bricehalder** [wikispeedruns/wikipedia-speedruns#280]
<img width="636" alt="Screen Shot 2022-03-28 at 8 20 12 PM" src="https://user-images.githubusercontent.com/17424008/160526581-f9d2a8af-c259-4f6e-b918-d696ef07454a.png">

Change this description to something better

**Comment by bricehalder** [comment]
<img width="613" alt="Screen Shot 2022-04-07 at 1 22 27 AM" src="https://user-images.githubusercontent.com/17424008/162154418-f135d950-a1f0-4b96-b573-264d0ac07a81.png">

Seems like Google re-indexed so probably good with this?

**Comment by dqian3** [comment]
It seems to have been fixed now by itself, we probably should look into this more though.
