### ISSUE TITLE
Add article previews for loading screen

### ISSUE THREAD

**Issue by bricehalder** [wikispeedruns/wikipedia-speedruns#283]

**Comment by dqian3** [comment]
In fact, I this can display automatically, rather than just as a tooltip. I.e. like left half of the screen shows start, right half shows end.

**Comment by bricehalder** [comment]
> In fact, I this can display automatically, rather than just as a tooltip. I.e. like left half of the screen shows start, right half shows end.

I think this would be good as an option, my concern is that it might look too busy as a default look

**Comment by mliu59** [comment]
If we want to include this, we may also want to increase the countdown timer to 20 seconds or something. Or else this would seem somewhat pointless. Good thing we also have the skip countdown button

**Comment by bricehalder** [comment]
I think this would be good as just the i bubble icon we currently use
