### ISSUE TITLE
Change Rollout

### ISSUE THREAD

**Issue by dqian3** [wikispeedruns/wikipedia-speedruns#285]
Change rollout to move version in main to prod periodically, rather than on pushing.

**Comment by bricehalder** [comment]
What's the background for this change, sorry might've missed it if it was discussed in the meeting. Is this just something that's good to do

**Comment by dqian3** [comment]
@bricehalder I'm changing our script so that we automatically rollout to beta, and we can manually push to prod when we feel like something is ready. Just finished setting it up, closing now.
