### ISSUE TITLE
Modularize tooltips so we can use them on all pages

### ISSUE THREAD

**Issue by mliu59** [wikispeedruns/wikipedia-speedruns#305]
The tooltip thing we have is really helpful. Potentially we can use it for many other UI elements on our entire website (home page, leaderboard, etc.)

We should have it modularized to be able to contain any generic content

**Comment by mliu59** [comment]
@maggarwal99 if you were to tackle this, just make sure its mobile compatible lmao

**Comment by maggarwal99** [comment]
Bootstrap has built-in tooltips and popovers that should be good for most use cases. We can also use BootstrapVue that ports Bootstrap modules as Vue components and directives.

1. [Bootstrap tooltips](https://getbootstrap.com/docs/5.0/components/tooltips/)
2. [Bootstrap popovers](https://getbootstrap.com/docs/5.0/components/popovers/)
3. [Bootstrap Vue tooltip component](https://bootstrap-vue.org/docs/components/tooltip)
4. [Bootstrap Vue tooltip directive](https://bootstrap-vue.org/docs/directives/tooltip)
