### ISSUE TITLE
Other people's runs displaying as "Your Last Run"

### ISSUE THREAD

**Issue by mliu59** [wikispeedruns/wikipedia-speedruns#392]
![image](https://user-images.githubusercontent.com/61032765/177583634-87109dee-d07e-4fe1-b5d0-2488a9f6cf85.png)

See leaderboard screenshot. On my own account I have never finished this prompt, but it shows "your last run" with a very large runtime. Might be some bug with switching views and poorly initialized values.

URL used: https://wikispeedruns.com/leaderboard/228?preset=shortest&offset=0

**Comment by dqian3** [comment]
Figured out the problem with this, it is aggregating all anonymous runs and showing that as your last run.
