### ISSUE TITLE
Run Summary for Quick Play could provide more information

### ISSUE THREAD

**Issue by crsven** [wikispeedruns/wikipedia-speedruns#443]
I'd like to propose that the Run Summary include the End Article and a link to play the same articles for Quick Play rounds. This would be more fun to share with friends who want to compete with a run idea.

Example:
```
Wiki Speedruns
Jaguar Cars to Ford Motor Company
2 🖱️
18.451999999999998 ⏱️
https://wikispeedruns.com/play/quick_play?prompt_start=Jaguar%20Cars&prompt_end=Ford%20Motor%20Company
```

**Comment by dqian3** [comment]
@danielliu04 Wanna take a look at this?

**Comment by bricehalder** [comment]
This could be a lot nicer with a custom url shortlinker (also a fun side project) 
e.g.
`wiki.speed/5nf12n` or something like that
