### ISSUE TITLE
Rotate marathon modes on wikispeedruns.com routinely

### ISSUE THREAD

**Issue by kylecarbs** [wikispeedruns/wikipedia-speedruns#452]
My friends and I enjoy doing the marathons in Discord. It'd be nice if these rotated on a daily/weekly basis kind of like Wordle.

**Comment by mliu59** [comment]
I think the biggest challenge to adding these prompts more frequently is that all prompts are generated completely manually. But now that we have a pretty reliable generator, it could be more semi-automated? Or add an option for community submitted marathon prompts to crowdsource

**Comment by kylecarbs** [comment]
If there were a repo to submit a new set of marathons, I'd happily submit a PR now and again.

**Comment by mliu59** [comment]
@kylecarbs We currently add prompts through a dedicated admin page, but I think it would be cool to integrate some community submitted prompt feature (for both marathon and sprints): #100. Then the admin just has to approve/reject

@dqian3 thoughts?

**Comment by dqian3** [comment]
Yeah, I think we can try doing that? We could add like a contribute link at the botton of the card and link to the marathon editing component (cleaned up hopefully). These do take a while to come up with though.

I think our random article generation might be good enough soon to create some good random marathon prompts, or at least assist with it. For now, it would be good to embed the generator into the marathon prompt creater.

**Comment by mliu59** [comment]
@kylecarbs finally added a new feature for this! #484
You can now submit sprint/marathon prompts on this page to be featured publically
https://wikispeedruns.com/contribute
