### ISSUE TITLE
Disruptive boxes in the middle of the website

### ISSUE THREAD

**Issue by masl** [wikispeedruns/wikipedia-speedruns#507]
There seems to be a conflict within CSS classes of wikispeedruns and the wikipedia page itself when playing in German language.

In the following GIF you can see that a small box in the center of the screen is constantly blocking the view:

![wikispeedrun_issue](https://github.com/wikispeedruns/wikipedia-speedruns/assets/48460840/83e6137e-0987-4c96-adf7-542cfe8e0600)
*Issue on the Wikipedia Speedrun Page*

You can try yourself here [https://wikispeedruns.com/play/quick_play?prompt_start=Deutschland&prompt_end=Niederlande&lang=de](https://wikispeedruns.com/play/quick_play?prompt_start=Deutschland&prompt_end=Niederlande&lang=de)

---

As I understand it, the CSS class "centered" of the *Wikipedia* page collides with the class "centered" of the *Wikipedia Speedruns* page, because the class is used on the *Wikipedia* content seen in the following image. At the same time, the [class](https://github.com/wikispeedruns/wikipedia-speedruns/blob/main/static/stylesheets/play.css#L149) with the same name is used on *Wikipedia Speedruns* to probably display such a centered box.

![wikipedia_footer](https://github.com/wikispeedruns/wikipedia-speedruns/assets/48460840/552f0852-1565-457a-8b9e-1d750f599f16)
*Wikipedia Page*
<br />

![wikispeedrun_footer](https://github.com/wikispeedruns/wikipedia-speedruns/assets/48460840/f5b09810-b397-4582-96ba-2007baadc92f)
*Wikipedia Speedrun Page*

**Comment by mliu59** [comment]
@Phiwatec thanks again for the fix!
