### ISSUE TITLE
Add Ads on the countdown timer when you click "play"

### ISSUE THREAD

**Issue by dsohn110** [wikispeedruns/wikipedia-speedruns#519]
- When "play" is clicked, the countdown timer can have an Ad or Ad Video
- Jason's skip feature can be used if you have a membership

**Comment by bricehalder** [comment]
<img width="734" alt="Screenshot 2023-11-19 at 12 11 47 AM" src="https://github.com/wikispeedruns/wikipedia-speedruns/assets/17424008/b5b52029-8b2b-49bd-b6ef-29f85bb3ff40">
