### ISSUE TITLE
Add more starting tips for the countdown page

### ISSUE THREAD

**Issue by mliu59** [wikispeedruns/wikipedia-speedruns#53]

**Comment by mliu59** [comment]
Can be implemented in #82

**Comment by mliu59** [comment]
https://docs.google.com/document/d/15kgDkeuHhYOGOW5DBnjLfXSG2dRjYLP_p0hvet29wGs/edit

**Comment by bricehalder** [comment]
@mliu59 Do we still need this issue/want more starting tips or is this good to close?

**Comment by mliu59** [comment]
@bricehalder I think we can close this for now, will reopen when we start a more dedicated UI content push
