### ISSUE TITLE
use a wikispeedruns logo with white text for dark mode

### ISSUE THREAD

**Issue by mliu59** [wikispeedruns/wikipedia-speedruns#536]
![image](https://github.com/wikispeedruns/wikipedia-speedruns/assets/61032765/13ecb39f-7301-4ff8-b67e-9045ddadcf4a)

**Comment by b3at1** [comment]
![image](https://github.com/wikispeedruns/wikipedia-speedruns/assets/94728927/8c0bcc6e-9d9a-4eb4-9d45-2a1c41242dfb)
I would like to contribute to fixing issues such as this but when I am running the server locally, it looks very empty and dark mode just shows a ternary. Is this expected and how can I fix this?

Thanks

**Comment by mliu59** [comment]
> ![image](https://github.com/wikispeedruns/wikipedia-speedruns/assets/94728927/8c0bcc6e-9d9a-4eb4-9d45-2a1c41242dfb)
> 
> I would like to contribute to fixing issues such as this but when I am running the server locally, it looks very empty and dark mode just shows a ternary. Is this expected and how can I fix this?
> 
> 
> 
> Thanks

Hey! Did you start the frontend build? See README for cmd to run

**Comment by b3at1** [comment]
I am running `npm run start` followed by `flask run` in a separate terminal. Not sure if this helps but it passed pytest

**Comment by mliu59** [comment]
![image](https://github.com/wikispeedruns/wikipedia-speedruns/assets/61032765/63e8cc61-b322-4085-b179-e107f4970316)
![image](https://github.com/wikispeedruns/wikipedia-speedruns/assets/61032765/ef6607d6-4562-460b-8b5d-3e69cb2d73d7)

Thanks @dqian3 and Oliver for the new logo. Looks great!
