### ISSUE TITLE
Add a refresh button for suggested quick play prompts

### ISSUE THREAD

**Issue by mliu59** [wikispeedruns/wikipedia-speedruns#552]
![image](https://github.com/wikispeedruns/wikipedia-speedruns/assets/61032765/f2fa1a1d-999c-427b-a2fa-4323b301fcdf)
Add a refresh button so players can get new suggestions when they want.

**Comment by amit-077** [comment]
Can you please elaborate more ? Do you just want a button that refreshes the page ?

**Comment by mliu59** [comment]
> Can you please elaborate more ? Do you just want a button that refreshes the page ?

This button/link should only update the suggested list of quick play prompts by just making another api call. The button should also be contained within the module: static/js/modules/quickPlaySuggestions.js

**Comment by dqian3** [comment]
Implemented in #597
