### ISSUE TITLE
Articles with special characters don't work as goal pages

### ISSUE THREAD

**Issue by bricehalder** [wikispeedruns/wikipedia-speedruns#590]
From Discord:
> hey hey! idk if you guys already know this but it seems articles with a "+" in them dont work properly
my target article was "springer science+business media", and i couldnt get it to count the win. the text that displays the target didnt show a "+", but the description was the exact same
you can also easily reproduce it by just setting the start to springer publishing and the target to springer science lol

https://discord.com/channels/936202186520678431/936212632866783333/1242872406368981012

**Comment by mliu59** [comment]
Confirmed fixed, closing issue
