### ISSUE TITLE
Add Play Again button to end screen

### ISSUE THREAD

**Issue by bricehalder** [wikispeedruns/wikipedia-speedruns#592]
For speedrunners, it makes sense to have a button to easily play again 

<img width="1130" alt="Screenshot 2024-05-23 at 6 19 01 PM" src="https://github.com/wikispeedruns/wikipedia-speedruns/assets/17424008/8ce40407-2a64-4dae-8979-4c5a4cc57d18">

**Comment by mhuangw** [comment]
Has this already been added?
![image](https://github.com/wikispeedruns/wikipedia-speedruns/assets/12538218/fe0f4169-6226-4c5d-87ea-479d6a800602)

**Comment by bricehalder** [comment]
> Or is it about replaying the same path

Yeah, replaying the same exact prompt. The play another round is kind of redundant with the return to home page

**Comment by dqian3** [comment]
Closed by #595
